### ISSUE TITLE
Issue with Python 2.6

### ISSUE THREAD

**Issue by cbertelli** [jkibele/acc-assess#2]
Hello,
I've found out an issue with python 2.6.
The line 
        localePath = os.path.join(self.plugin_dir, 'mask_{}.qm'.format(locale))
in aeag_mask.py should be
        localePath = os.path.join(self.plugin_dir, 'mask_{0}.qm'.format(locale))
for python 2.6 compatibility.

**Comment by jkibele** [comment]
Oops, I managed to miss the notification when this comment was made. Sorry for taking so long to respond. 

I don't recognize `aeag_mask.py`. It's not part of my plugin code and it doesn't seem to be part of any of my plugin's dependencies (as far as I can tell). A google search for "aeag_mask.py" turned up links to [this plugin](https://github.com/aeag/mask_plugin).

Also, my code sets `localePath` like this:

``` python
localePath = os.path.join(self.plugin_dir, 'i18n', 'accassess_{}.qm'.format(locale))
```

...and that's the only place that `localePath` gets set in my code. So I don't think this issue is mine.
